version: '3'

services:
  db:
    image: mysql:5.7
    command: "--innodb-use-native-aio=0 --explicit_defaults_for_timestamp"
    container_name: db
    restart: always
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/scripts/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    command: yarn start
    depends_on:
      - db
    networks:
      - app
    volumes:
      - ./node:/usr/app/node
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:8080
    depends_on:
      - node
    networks:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d

networks:
  app:
    driver: bridge
